### PR TITLE
Updated dependencies, testing with newest Node version, added type definition

### PR DESCRIPTION
**Pull request by prokopsimek**
### Added
1. Type definition
2. npm package keywords in `package.json`

### Changed
1. Refactored algorithm by @seriousme in #25 
2. Updated Travis CI to run on Node v8 and above
3. Modernize Readme
4. Replaced `var` for `const` or `let`

---

@novemberborn Please review.

### CODE REVIEW

**Review by novemberborn — CHANGES_REQUESTED** [review]
Thanks for the PR @prokopsimek!

I think TypeScript is overkill for as small a project as this. Would you mind taking it back out? Happy to include an `index.d.ts` file though.

Let's remove the package lock as well, and disable it using `.npmrc`.

**Comment by prokopsimek** [comment]
@novemberborn As you wish :) But I don't understand why you want to disable package lock?

**Comment by prokopsimek** [comment]
> ## List of changes
> ### Added
> 1. Type definition
> 2. npm package keywords in `package.json`
> 
> ### Changed
> 1. Refactored algorithm by @seriousme in #25
> 2. Updated Travis CI to run on Node v8 and above
> 3. Modernize Readme
> 4. Replaced `var` for `const` or `let`
> 
> @novemberborn Please review.

@novemberborn I have updated the PR and the description :) Feel free to review.

**Comment by novemberborn** [comment]
@prokopsimek thanks! I made some changes but I couldn't push them to your fork. Would you mind reviewing https://github.com/novemberborn/common-path-prefix/pull/30?

**Pull request closed without merging**
