### PR TITLE
Simplified algorithm

### PR DESCRIPTION
**Pull request by seriousme**
Hi,

I've simplified the algorithm to speed it up.
It now reduces the prefix on every next path and stops immediately if no valid common prefix can be found.

Cheers,
Hans

### CODE REVIEW

**Comment by novemberborn** [comment]
Hi @seriousme, this seems pretty cool! Haven't had a chance yet to look at this in detail but hope to do so soon.

**Comment by novemberborn** [comment]
@seriousme I found one edge case: multi-byte strings:

```js
test('the file separator can be a multi-byte string', t => {
  t.is(commonPathPrefix(['foo👼bar👼baz', 'foo👼bar👼qux'], '👼'), 'foo👼bar👼')
})
```

I'd be OK with requiring `sep` to be a single-byte string, though we should either add an assertion or document it. What do you think?

What led you to making these performance enhancements?

**Comment by seriousme** [comment]
Ok, I have fixed it  with minimal overhead (using ES6) and it now passes all 6 tests + the additional 7th test which I also added to the test set.

Reason for fixing was that I was looking for common path prefix functionality, stumbled across your module and thought: it should be possible to optimize this a bit. So curiosity took over and there was the PR.

**Comment by seriousme** [comment]
Darn, Travis fails because of the older versions of Node 
(should have thought about that myself :-()

**Comment by seriousme** [comment]
Ok, backported the algorithm for older versions. It has changed a little as it now splits each path into components and compares components.

**Comment by novemberborn** [comment]
> Darn, Travis fails because of the older versions of Node
> (should have thought about that myself :-()

Heh. I can make some changes tomorrow to drop support for 0.10 and 0.12. (Basically repeating https://github.com/novemberborn/package-hash/commit/b8650c84c39bc1ab9aa0e5d183b618aeb8d0631e for this repo.) It should still support Node.js 4, which means no spread operator. You can use `for/of` to iterate over the strings though.

Of course whether *that* is *actually* faster remains to be seen. I like your approach though, much better than counting all potential prefix strings…

> Reason for fixing was that I was looking for common path prefix functionality, stumbled across your module and thought: it should be possible to optimize this a bit. So curiosity took over and there was the PR.

Would you be interested in having commit & publish access? 😄

**Comment by seriousme** [comment]
Nice to read you like the approach :-)

Dropping old versions of Node could be an option, but then again: if it works it works.

Whether the new algorithm is actually faster would need to be proven in real life usage, but being able to skip the sort should already beat the original algorithm. Not that I think people are really suffering right now as I don't expect people to spend a large percent of their cycles on this functionality ;-)

Thanks for offering commit & publish acces, but I'll decline, I was just passing by and had some fun in satisfying my curiosity ;-)

Cheers,
Hans

**Comment by prokopsimek** [comment]
@novemberborn merge pls ❤️

**Comment by novemberborn** [comment]
@prokopsimek would you be interested in picking this up?

There haven't been any changes here in the past two years, so first we'd have to remove Greenkeeper, update the supported Node.js versions, update dependencies (replace `@novemberborn/as-i-preach` with `standard`). And then revisit this PR.

**Comment by prokopsimek** [comment]
@novemberborn Hi, I'll try to make a PR in next week :)

**Comment by novemberborn** [comment]
Included with #30.

**Pull request closed without merging**
